### ISSUE TITLE
Unable to read octree from .bt file

### ISSUE THREAD

**Issue by Abhishek-EE** [wkentaro/octomap-python#10]
Hello, I was trying to use octomap-python to read the binary tree stored in .bt file but it throws this error, the error logs are as follows, 

`  File "/Users/abhishekranjansingh/opt/anaconda3/envs/path-generator/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Users/abhishekranjansingh/opt/anaconda3/envs/path-generator/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/abhishekranjansingh/.vscode/extensions/ms-python.python-2022.0.1814523869/pythonFiles/lib/python/debugpy/__main__.py", line 45, in <module>
    cli.main()
  File "/Users/abhishekranjansingh/.vscode/extensions/ms-python.python-2022.0.1814523869/pythonFiles/lib/python/debugpy/../debugpy/server/cli.py", line 444, in main
    run()
  File "/Users/abhishekranjansingh/.vscode/extensions/ms-python.python-2022.0.1814523869/pythonFiles/lib/python/debugpy/../debugpy/server/cli.py", line 285, in run_file
    runpy.run_path(target_as_str, run_name=compat.force_str("__main__"))
  File "/Users/abhishekranjansingh/opt/anaconda3/envs/path-generator/lib/python3.9/runpy.py", line 268, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/Users/abhishekranjansingh/opt/anaconda3/envs/path-generator/lib/python3.9/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/Users/abhishekranjansingh/opt/anaconda3/envs/path-generator/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/abhishekranjansingh/dev/cptsp-solver/cptsp_solver/main.py", line 41, in <module>
    octree = octomap.OcTree("AIR_A320_200.bt")
  File "octomap/octomap.pyx", line 322, in octomap.OcTree.__cinit__
TypeError: expected bytes, str found`

When i try using readBinary(string) function it says:
`Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "octomap[/octomap.pyx]()", line 439, in octomap.OcTree.readBinary
TypeError: startswith first arg must be str or a tuple of str, not bytes`

If anyone has any alternative to my current approach the help would be highly appreciated.

**Comment by wkentaro** [comment]
Can you give a sample .bt file to debug?

**Comment by Abhishek-EE** [comment]
Hi @wkentaro, 
Thanks for such quick response. Sure, here is the link for the file https://drive.google.com/file/d/1pWoAS4JcN3GUg5wmmkHvUXw-kzPGDHhy/view?usp=sharing

**Comment by wkentaro** [comment]
Not ideal, but you can use `.encode()` as a workaround.

```python
octree = octomap.OcTree("./AIR_A320_200.bt".encode())
```

**Comment by Abhishek-EE** [comment]
Thanks for the being so apt, this works. I think the readBinary function would also work if I encode the input.

**Comment by wkentaro** [comment]
> *This was generated by AI during triage.*

## Agent Brief

**Category:** bug
**Summary:** `OcTree(...)`, `readBinary`, `read`, `write`, and `writeBinary` reject `str` paths, accepting only `bytes`.

**Current behavior:**
Passing a plain Python `str` filename fails:
- `octomap.OcTree("foo.bt")` raises `TypeError: expected bytes, str found` (the constructor casts the argument straight to a C `char*`, which requires `bytes`).
- `octree.readBinary("foo.bt")` raises `TypeError: startswith first arg must be str or a tuple of str, not bytes` (the method uses a `bytes` literal in a `.startswith(...)` check against the `str` argument to distinguish raw-binary-data input from a file path).

The same `bytes`-only assumption exists in the `read()` and `write()` paths. Today users must call `.encode()` themselves (the documented workaround). Existing tests only pass `bytes` literals, so the `str` path is untested.

**Desired behavior:**
All of these entry points accept either `str` or `bytes` for the filename / data argument. A `str` is coerced to `bytes` (UTF-8) internally before reaching the C++ layer, so `octomap.OcTree("foo.bt")` and `octree.readBinary("foo.bt")` work without manual encoding. `bytes` input continues to work unchanged, including the existing "raw serialized data vs. file path" discrimination in `read`/`readBinary`.

**Key interfaces:**
- The `OcTree` constructor that takes a filename/resolution argument.
- `OcTree.readBinary`, `OcTree.read`, `OcTree.writeBinary`, `OcTree.write` (and the module-level read/write helpers they delegate to).
- The header-sniffing logic that decides whether the argument is serialized data or a path must operate on `bytes` consistently regardless of whether a `str` or `bytes` was passed.

**Acceptance criteria:**
- [ ] `octomap.OcTree("path.bt")` (str) constructs without `TypeError`.
- [ ] `octree.readBinary("path.bt")` and `octree.read("path.ot")` accept a `str` path.
- [ ] `octree.writeBinary("path.bt")` / `octree.write("path.ot")` accept a `str` path.
- [ ] Passing `bytes` to all of the above still works (no regression), including the raw-serialized-data branch of `read`/`readBinary`.
- [ ] A write-then-read round-trip using `str` paths is covered by a test alongside the existing `bytes`-based tests.

**Out of scope:**
- `pathlib.Path` support (can be a follow-up; this issue is `str` vs `bytes`).
- Any change to the binary/serialized format itself.
