### ISSUE TITLE
Error with PIP install

### ISSUE THREAD

**Issue by Nico-oe** [wkentaro/octomap-python#14]
Hey everyone, 

I get the following error trying to install the octomap-python library using pip. Can anyone help?

![cmake_error](https://user-images.githubusercontent.com/80453506/170198128-180dc303-9a22-42f6-a81d-871cb2c8d316.png)

Thanks in advance. 

Kind regards, 

Nico

**Comment by jllv** [comment]
any updates on this issue? I'm running into the same error message (python3.9 on win11), did you find a solution?

**Comment by aprath1** [comment]
did any one manage to resolve this issue?

I am getting the following Error:

```
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> octomap-python

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.
--- Logging error ---
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/pip/_internal/utils/logging.py", line 177, in emit
    self.console.print(renderable, overflow="ignore", crop=False, style=style)
  File "/usr/local/lib/python3.8/dist-packages/pip/_vendor/rich/console.py", line 1752, in print
    extend(render(renderable, render_options))
  File "/usr/local/lib/python3.8/dist-packages/pip/_vendor/rich/console.py", line 1390, in render
    for render_output in iter_render:
  File "/usr/local/lib/python3.8/dist-packages/pip/_internal/utils/logging.py", line 134, in __rich_console__
    for line in lines:
  File "/usr/local/lib/python3.8/dist-packages/pip/_vendor/rich/segment.py", line 245, in split_lines
    for segment in segments:
  File "/usr/local/lib/python3.8/dist-packages/pip/_vendor/rich/console.py", line 1368, in render
    renderable = rich_cast(renderable)
  File "/usr/local/lib/python3.8/dist-packages/pip/_vendor/rich/protocol.py", line 36, in rich_cast
    renderable = cast_method()
  File "/usr/local/lib/python3.8/dist-packages/pip/_internal/self_outdated_check.py", line 130, in __rich__
    pip_cmd = get_best_invocation_for_this_pip()
  File "/usr/local/lib/python3.8/dist-packages/pip/_internal/utils/entrypoints.py", line 58, in get_best_invocation_for_this_pip
    if found_executable and os.path.samefile(
  File "/usr/lib/python3.8/genericpath.py", line 101, in samefile
    s2 = os.stat(f2)
FileNotFoundError: [Errno 2] No such file or directory: '/usr/bin/pip3.8'
```

**Comment by jllv** [comment]
@aprath1 I switched to Ubuntu, couldn't get my error resolved on Windows. I had to tweak some bits but its working for me now

**Comment by dragancevs** [comment]
> @aprath1 I switched to Ubuntu, couldn't get my error resolved on Windows. I had to tweak some bits but its working for me now

Hello, how have you installed it on Ubuntu? I'm trying to install it, but it show me only errors.

**Comment by jllv** [comment]
I installed some dependencies (not sure if that was even necessary, but shouldn't hurt either) with: 
`apt-get install libqt5opengl5-dev libqt5svg5-dev cmake`, `pip install cmake`

Now, `pip install octomap-python` should work as far as I remember. I think I had an issue where pip installed the files to /home/username/.local/lib, so I copied the relevant files from this directory into /usr/local/lib. I hope I didn't miss a step, but that should do the trick.

**Comment by BobbyCephy** [comment]
Hey, I am getting the following error:
`src/octomap/octomap/src/binvox2bt.cpp:230:9: error: reference to ‘byte’ is ambiguous`

This can be solved by setting the C++ standard to 11:
`CXXFLAGS="-std=c++11" pip install octomap-python`

**Comment by wkentaro** [comment]
> *This was generated by AI during triage.*

Triage note: this report is hard to action as-is. The original description is a screenshot only, with no copyable error text, Python version, or OS. The follow-up comments show several *different* build failures collapsed under one title:
- C++ standard clash (`reference to 'byte' is ambiguous`) when OctoMap 1.8.0 is built under C++17 — worked around with `CXXFLAGS="-std=c++11"`, and `setup.py` now passes `-DCMAKE_CXX_STANDARD=14`;
- missing build-time `cmake` / Qt dev packages on some systems;
- Windows/MSVC toolchain issues.

The durable fix is the in-flight build overhaul rather than a one-off patch here: #27 (scikit-build-core + statically linked extension) removes the bootstrap/linking fragility, and #33 (cibuildwheel) ships prebuilt wheels so `pip install` needs no compiler or system OctoMap at all. #29 (OctoMap v1.10.0) also removes the `byte` ambiguity. Related install reports: #18, #22.

Parking in `needs-triage` for @wkentaro: recommend closing as superseded once #27/#33 land (or keep as a tracking umbrella for install failures). I won't close it. If you'd prefer to keep it actionable, the original reporter would need to supply the exact error text, OS, and Python version.

**Comment by wkentaro** [comment]
> *This was generated by AI during triage.*

Fixed. octomap-python now ships **prebuilt binary wheels** (manylinux x86_64/aarch64, macOS arm64), so `pip install` no longer compiles via CMake on those platforms — the old build error no longer applies. Reopen if you hit a build issue on the latest release.
